from dataclasses import dataclass
import datetime


@dataclass
class DataStorage:
    PLAY_ZONES = [
        {
            "id": 1,
            "play_zone_title": "Європа",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/europe.png"
        },
        {
            "id": 2,
            "play_zone_title": "Азія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/asia.png"
        },
        {
            "id": 3,
            "play_zone_title": "Африка",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/africa.png"
        },
        {
            "id": 4,
            "play_zone_title": "Південна Америка",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/south-america.png",
        },
        {
            "id": 5,
            "play_zone_title": "Північна & Центральна Америка",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/north-and-central-america.png"
        },
        {
            "id": 6,
            "play_zone_title": "Океанія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/oceania.png"
        },
        {
            "id": 7,
            "play_zone_title": "Англія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/en.png"
        },
        {
            "id": 8,
            "play_zone_title": "Іспанія",
            "play_zone_area_image": 'https://www.sofascore.com/static/images/flags/es.png'
        },
        {
            "id": 9,
            "play_zone_title": "Німеччина",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/de.png"
        },
        {
            "id": 10,
            "play_zone_title": "Італія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/it.png"
        },
        {
            "id": 11,
            "play_zone_title": "Франція",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/fr.png"
        },
        {
            "id": 12,
            "play_zone_title": "Нідерланди",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/nl.png"
        },
        {
            "id": 13,
            "play_zone_title": "Бразилія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/br.png"
        },
        {
            "id": 14,
            "play_zone_title": "Україна",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/ua.png"
        },
        {
            "id": 15,
            "play_zone_title": "Історія чемпіонату світу",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/international.png"
        },
        {
            "id": 16,
            "play_zone_title": "Австралія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/au.png"
        },
        {
            "id": 17,
            "play_zone_title": "Австрія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/at.png"
        },
        {
            "id": 18,
            "play_zone_title": "Австрія Любительська",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/at.png"
        },
        {
            "id": 19,
            "play_zone_title": "Азербайджан",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/az.png"
        },
        {
            "id": 20,
            "play_zone_title": "Албанія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/al.png"
        },
        {
            "id": 21,
            "play_zone_title": "Алжир",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/dz.png",
        },
        {
            "id": 22,
            "play_zone_title": "Американське Самоа",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/as.png"
        },
        {
            "id": 23,
            "play_zone_title": "Ангілья",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/ai.png"
        },
        {
            "id": 24,
            "play_zone_title": "Англія Любительська",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/en.png"
        },
        {
            "id": 25,
            "play_zone_title": "Ангола",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/ao.png"
        },
        {
            "id": 26,
            "play_zone_title": "Андорра",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/ad.png"
        },
        {
            "id": 27,
            "play_zone_title": "Антигуа і Барбуда",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/ag.png"
        },
        {
            "id": 28,
            "play_zone_title": "Аргентина",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/ar.png",
        }
    ]

    ALL_LEAGUES = [
        {
            "league_title": "A-League Men",
            "slug": "a-league-men",
            "primary_color_hex": "#fe5001",
            "secondary_color_hex": "#8e0a06",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/136/image",
            "most_titles": 5,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-10-26",
            "end_date": "2024-05-31",
            "play_zone": 16
        },
        {
            "league_title": "A-League Women",
            "slug": "a-league-women",
            "primary_color_hex": "#a21c13",
            "secondary_color_hex": "#e44134",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/136/image",
            "most_titles": 4,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-10-13",
            "end_date": "2024-05-04",
            "play_zone": 16
        },
        {
            "league_title": "Australia Cup",
            "slug": "australia-cup",
            "primary_color_hex": "#16263c",
            "secondary_color_hex": "#6895cf",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1786/image",
            "most_titles": 3,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-17",
            "end_date": "2023-10-09",
            "play_zone": 16
        },
        {
            "league_title": "National Premier League Finals",
            "slug": "national-premier-league-finals",
            "primary_color_hex": "#0c2340",
            "secondary_color_hex": "#0086e1",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1510/image",
            "most_titles": 0,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-21",
            "end_date": "2023-10-07",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Capital Football",
            "slug": "npm-capital-football",
            "primary_color_hex": "#1483be",
            "secondary_color_hex": "#189ce6",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1260/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-04-05",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, New South Wales",
            "slug": "npm-new-south-wales",
            "primary_color_hex": "#5ab6e6",
            "secondary_color_hex": "#1b4880",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1274/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-16",
            "end_date": "2024-09-08",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Northern New South Wales",
            "slug": "npl-northern-new-south-wales",
            "primary_color_hex": "#b5151b",
            "secondary_color_hex": "ed1c24",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1638/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-11",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Queensland",
            "slug": "npl-queensland",
            "primary_color_hex": "#53081e",
            "secondary_color_hex": "#ba1b53",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1268/image",
            "most_titles": 3,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-06",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Queensland, Women",
            "slug": "npl-queensland-women",
            "primary_color_hex": "#53081e",
            "secondary_color_hex": "#ba1b53",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/10476/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-09",
            "end_date": "2024-09-06",
            "play_zone": 16
        },
        {
            "league_title": "NPL, South Australia",
            "slug": "npl-south-australia",
            "primary_color_hex": "#004f8b",
            "secondary_color_hex": "#c31c34",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1258/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, South Australia, Women",
            "slug": "npl-south-australia-women",
            "primary_color_hex": "#004f8b",
            "secondary_color_hex": "#c31c34",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14723/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-15",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Tasmania",
            "slug": "npl-tasmania",
            "primary_color_hex": "#009f46",
            "secondary_color_hex": "#005c2f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1626/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-15",
            "end_date": "2024-10-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Victoria",
            "slug": "npl-victoria",
            "primary_color_hex": "#005e9c",
            "secondary_color_hex": "#004673",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1275/image",
            "most_titles": 4,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-08",
            "end_date": "2024-09-08",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Western Australia",
            "slug": "npl-western-australia",
            "primary_color_hex": "#ffb20e",
            "secondary_color_hex": "#694c06",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1270/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-16",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "Brisbane Premier League",
            "slug": "brisbane-premier-league",
            "primary_color_hex": "#979691",
            "secondary_color_hex": "#4388cd",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1248/image",
            "most_tiles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-05",
            "end_date": "2024-10-17",
            "play_zone": 16
        },
        {
            "league_title": "Brisbane Premier League, Women",
            "slug": "brisbane-premier-league-women",
            "primary_color_hex": "#0fbaf2",
            "secondary_color_hex": "#0ea3d3",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14722/image",
            "most_titles": 0,
            "tier": 2,
            "start_date": "2024-05-12",
            "end_date": "2024-10-17",
            "play_zone": 16
        },
        {
            "league_title": "A-League Youth",
            "slug": "a-league-youth",
            "primary_color_hex": "#b71100",
            "secondary_color_hex": "#ff4000",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14404/image",
            "most_titles": 0,
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-11-16",
            "end_date": "2024-02-20",
            "play_zone": 16
        },
        {
            "league_title": "Queensland Premier League 1",
            "slug": "queensland-premier-league-1",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "most_titles": 0,
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-07",
            "play_zone": 16
        },
        {
            "league_title": "Bundesliga",
            "slug": "bundesliga",
            "primary_color_hex": "#b80a0c",
            "secondary_color_hex": "#eb544a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/45/image",
            "most_titles": 32,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-28",
            "end_date": "2024-06-02",
            "play_zone": 17
        },
        {
            "league_title": "ÖFB Cup",
            "slug": "ofb-cup",
            "primary_color_hex": "#dc2e25",
            "secondary_color_hex": "#0065b1",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/445/image",
            "most_titles": 27,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-20",
            "end_date": "2024-05-01",
            "play_zone": 17
        },
        {
            "league_title": "2. Liga",
            "slug": "2-liga",
            "primary_color_hex": "#ea1013",
            "secondary_color_hex": "#b5b5b5",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/135/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-28",
            "end_date": "2024-05-26",
            "play_zone": 17,
        },
        {
            "league_title": "Frauen Bundesliga",
            "primary_color_hex": "#cc0033",
            "secondary_color_hex": "#ad536a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/9415/image",
            "most_titles": 0,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-25",
            "end_date": "2024-06-02",
            "play_zone": 17
        },
        {
            "league_title": "Regionalliga Ost",
            "slug": "regionalliga-ost",
            "primary_color_hex": "#970800",
            "secondary_color_hex": "#8d8d8d",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/166/image",
            "most_titles": 0,
            "tier": 3,
            "start_date": "2023-08-28",
            "end_date": "2024-06-02",
            "play_zone": 18
        },
        {
            "league_title": "Regionalliga Mitte",
            "slug": "regionalliga-mitte",
            "primary_color_hex": "#037a3c",
            "secondary_color_hex": "#909090",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/168/image",
            "most_titles": 0,
            "tier": 3,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-28",
            "end_date": "2024-06-09",
            "play_zone": 18
        },
        {
            "league_title": "Regionalliga West",
            "slug": "regionalliga-west",
            "primary_color_hex": "#006699",
            "secondary_color_hex": "#81c9f1",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/167/image",
            "most_titles": 0,
            "tier": 3,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-28",
            "end_date": "2024-06-09",
            "play_zone": 18
        },
        {
            "league_title": "Misli Premier League",
            "slug": "misli-premier-league",
            "primary_color_hex": "#3449b2",
            "secondary_color_hex": "#1b157f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/709/image",
            "most_titles": 10,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-04",
            "end_date": "2024-05-31",
            "play_zone": 19
        },
        {
            "league_title": "Birinci Liqa",
            "slug": "birinci-liqa",
            "primary_color_hex": "#fde900",
            "secondary_color_hex": "#01923e",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/736/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-13",
            "end_date": "2024-05-31",
            "play_zone": 19
        },
        {
            "league_title": "Ikinci Liqa",
            "slug": "ikinci-liqa",
            "logo": "https://api.sofascore.app/api/v1/unique-tournament/21050/image",
            "most_titles": 0,
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-01",
            "end_date": "2024-06-01",
            "play_zone": 19
        },
        {
            "league_title": "Azerbaijan Cup",
            "slug": "azerbaijan-cup",
            "primary_color_hex": "#a2a5ca",
            "secondary_color_hex": "#6f95b7",
            "logo": "https://api.sofascore.app/api/v1/unique-tournament/740/image",
            "most_titles": 7,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": False,
            "start_date": "2023-11-18",
            "end_date": "2024-06-02",
            "play_zone": 19
        },
        {
            "league_title": "AFC Champions League",
            "slug": "afc-champions-league",
            "primary_color_hex": "#0050d4",
            "secondary_color_hex": "#fe9700",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/463/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-15",
            "end_date": "2024-05-25",
            "play_zone": 2
        },
        {
            "league_title": "AFC Cup",
            "slug": "afc-cup",
            "primary_color_hex": "#033aa7",
            "secondary_color_hex": "#d10007",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/668/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-08",
            "end_date": "2024-05-05",
            "play_zone": 2
        },
        {
            "league_title": "World Championship Qual.AFC",
            "slug": "world-championship-qual-afc",
            "primary_color_hex": "#9a1133",
            "secondary_color_hex": "#c11541",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/308/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-10-12",
            "end_date": "2025-11-25",
            "play_zone": 2
        },
        {
            "league_title": "AFC Asian Cup",
            "slug": "afc-asian-cup",
            "primary_color_hex": "#FCBD00",
            "secondary_color_hex": "#FC1302",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/246/image",
            "most_titles": 4,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2024-01-12",
            "end_date": "2024-02-10",
            "play_zone": 2
        },
        {
            "league_title": "AFC Asian Cup Qual.",
            "slug": "afc-asian-cup-qual",
            "primary_color_hex": "#ff2816",
            "secondary_color_hex": "#bfbfbf",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/28/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2021-10-07",
            "end_date": "2022-06-14",
            "play_zone": 2
        },
        {
            "league_title": "AFC Asian Cup, Women",
            "slug": "afc-asian-cup-women",
            "primary_color_hex": "#f3a953",
            "secondary_color_hex": "#19bc55",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1692/image",
            "most_titles": 10,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-01-20",
            "end_date": "2023-02-06",
            "play_zone": 2
        },
        {
            "league_title": "AFF Mitsubishi Electric Cup",
            "slug": "aff-mitsubishi-electric-cup",
            "primary_color_hex": "#005da3",
            "secondary_color_hex": "#e31079",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/602/image",
            "most_titles": 6,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2022-12-20",
            "end_date": "2023-01-16",
            "play_zone": 2
        },
        {
            "league_title": "Asian Games",
            "slug": "asian-games",
            "primary_color_hex": "#0c3ad2",
            "secondary_color_hex": "#ad28b5",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1862/image",
            "most_titles": 6,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2023-09-19",
            "end_date": "2023-10-07",
            "play_zone": 2
        },
        {
            "league_title": "AFC Olympic Qualification, Women",
            "slug": "afc-olympic-qualification-women",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/3082/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-10-26",
            "end_date": "2024-02-28",
            "play_zone": 2
        },
        {
            "league_title": "Asian Games, Women",
            "slug": "asian-games-women",
            "primary_color_hex": "#da0e7d",
            "secondary_color_hex": "#b225b7",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/11330/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-09-21",
            "end_date": "2023-10-06",
            "play_zone": 2
        },
        {
            "league_title": "East Asian Championship",
            "slug": "east-asian-championship",
            "primary_color_hex": "#1e4559",
            "secondary_color_hex": "#7bacc4",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/392/image",
            "most_titles": 5,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2022-07-19",
            "end_date": "2022-07-28",
            "play_zone": 2
        },
        {
            "league_title": "East Asian Championship, Women",
            "slug": "east-asian-championship-women",
            "primary_color_hex": "#1e4559",
            "secondary_color_hex": "#7bacc4",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/404/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2022-07-19",
            "end_date": "2022-07-26",
            "play_zone": 2
        },
        {
            "league_title": "Gulf Cup",
            "slug": "gulf-cup",
            "primary_color_hex": "#632c31",
            "secondary_color_hex": "#c5566f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/622/image",
            "most_titles": 10,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2023-01-06",
            "end_date": "2023-01-19",
            "play_zone": 2
        },
        {
            "league_title": "King`s Cup",
            "slug": "kings-cup",
            "primary_color_hex": "#01023b",
            "secondary_color_hex": "#e8124a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/10416/image",
            "most_titles": 15,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-07",
            "end_date": "2023-09-10",
            "play_zone": 2
        },
        {
            "league_title": "SAFF Championship",
            "slug": "saff-championship",
            "primary_color_hex": "#8779b4",
            "secondary_color_hex": "#f27501",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2354/image",
            "most_titles": 9,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-06-21",
            "end_date": "2023-07-04",
            "play_zone": 2
        },
        {
            "league_title": "Southeast Asian Games, Women",
            "slug": "southeast-asian-games-women",
            "primary_color_hex": "#375dab",
            "secondary_color_hex": "#f8971f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14527/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-05-03",
            "end_date": "2023-05-15",
            "play_zone": 2
        },
        {
            "league_title": "WAFF Championship",
            "slug": "waff-championship",
            "primary_color_hex": "#ee2128",
            "secondary_color_hex": "#128e47",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/842/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2019-07-30",
            "end_date": "2019-08-15",
            "play_zone": 2
        },
        {
            "league_title": "U23 AFC Asian Cup",
            "slug": "u23-afc-acian-cup",
            "primary_color_hex": "#73addc",
            "secondary_color_hex": "#d46c9d",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2349/image",
            "most_titles": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-04-15",
            "end_date": "2024-05-03",
            "play_zone": 2
        },
        {
            "league_title": "U23 AFC Asian Cup, Qualification",
            "slug": "u23-afc-asian-cup-qualification",
            "primary_color_hex": "#73addc",
            "secondary_color_hex": "#d46c9d",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2348/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-09-04",
            "end_date": "2023-09-12",
            "play_zone": 2
        },
        {
            "league_title": "U23 WAFF Championship",
            "slug": "u23-waff-championship",
            "primary_color_hex": "#ff0000",
            "secondary_color_hex": "#ff6a6a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2157/image",
            "most_titles": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-03-20",
            "end_date": "2024-03-26",
            "play_zone": 2
        },
        {
            "league_title": "U20 AFC Asian Cup",
            "slug": "u20-afc-asian-cup",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19546/image",
            "most_titles": 12,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-03-01",
            "end_date": "2023-03-18",
            "play_zone": 2
        },
        {
            "league_title": "U17 AFC Asian Cup",
            "slug": "u17-afc-asian-cup",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/20163/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-06-15",
            "end_date": "2023-07-02",
            "play_zone": 2
        },
        {
            "league_title": "AFC Women`s Club Championship",
            "slug": "afc-womens-club-championship",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/21453/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-11-06",
            "end_date": "2024-06-06",
            "play_zone": 2
        },
        {
            "league_title": "U17 AFC Asian Cup, Women",
            "slug": "u17-afc-asian-cup-women",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/22103/image",
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-06-06",
            "end_date": "2024-06-19",
            "play_zone": 2
        },
        {
            "league_title": "U20 AFC Asian Cup, Women",
            "slug": "u20-afc-asian-cup-women",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/21791/image",
            "most_titles": 6,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-03-03",
            "end_date": "2024-03-16",
            "play_zone": 2
        },
        {
            "league_title": "Abissnet Superiore",
            "slug": "abissnet-superiore",
            "primary_color_hex": "#c30000",
            "secondary_color_hex": "#646464",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/720/image",
            "most_titles": 26,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-19",
            "end_date": "2024-06-04",
            "play_zone": 20
        },
        {
            "league_title": "Kategoria e Pare",
            "slug": "kategoria-e-pare",
            "primary_color_hex": "#b00000",
            "secondary_color_hex": "#5c5c5c",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/722/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-09-02",
            "end_date": "2024-05-15",
            "play_zone": 20
        },
        {
            "league_title": "Kategorie e Dytë",
            "slug": "kategoria-e-dyte",
            "primary_color_hex": "#d3021",
            "secondary_color_hex": "#b3b3b3",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/16672/image",
            "most_titles": 4,
            "tier": 3,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-09-20",
            "end_date": "2024-05-04",
            "play_zone": 20
        },
        {
            "league_title": "Kategorie e Tretë",
            "slug": "kategorie-e-trete",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/16794/image",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-11-11",
            "end_date": "2023-05-15",
            "play_zone": 20
        },
        {
            "league_title": "Kupa e Shqiperise",
            "slug": "kupa-e-shqiperise",
            "primary_color_hex": "#c12e37",
            "secondary_color_hex": "#a5a4aa",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/756/image",
            "most_titles": 16,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-10-17",
            "end_date": "2024-05-14",
            "play_zone": 20
        },
        {
            "league_title": "Supercup",
            "slug": "supercup",
            "primary_color_hex": "#e51b24",
            "secondary_color_hex": "#22000",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1107/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-12-20",
            "end_date": "2023-12-21",
            "play_zone": 20
        },
        {
            "league_title": "Ligue 1",
            "slug": "ligue-1",
            "primary_color_hex": "#7eaa1f",
            "secondary_color_hex": "#f34720",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/841/image",
            "most_titles": 14,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-15",
            "end_date": "2024-07-15",
            "play_zone": 21
        },
        {
            "league_title": "League 2",
            "slug": "league-2",
            "primary_color_hex": "#94ca2d",
            "secondary_color_hex": "#f34620",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/9459/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-22",
            "end_date": "2023-06-03",
            "play_zone": 21
        },
        {
            "league_title": "Algerian Cup",
            "slug": "algerian-cup",
            "primary_color_hex": "#1e8d46",
            "secondary_color_hex": "#d7201d",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1588/image",
            "most_titles": 8,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-02",
            "end_date": "2023-06-23",
            "play_zone": 21
        },
        {
            "league_title": "Coupe de la Ligue",
            "slug": "coupe-de-la-ligue",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/16895/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2020-04-16",
            "end_date": "2021-08-10",
            "play_zone": 21
        },
        {
            "league_title": "Ligue 1, Reserves",
            "slug": "ligue-1-reserves",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-14",
            "end_date": "2024-06-30",
            "play_zone": 21
        },
        {
            "league_title": "FFAS Senior League",
            "slug": "ffas-senior-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/21134/image",
            "most_titles": 8,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2023-12-31",
            "play_zone": 22
        },
        {
            "league_title": "AFA Senior Male League",
            "slug": "afa-senior-male-league",
            "primary_color_hex": "#8ce2f1",
            "secondary_color_hex": "#f47e00",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/16721/image",
            "most_titles": 10,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-02-10",
            "end_date": "2024-06-09",
            "play_zone": 23
        },
        {
            "league_title": "President`s Cup",
            "slug": "presidents-cup",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/21918/image",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-01-13",
            "end_date": "2024-02-10",
            "play_zone": 23
        },
        {
            "league_title": "Championship",
            "slug": "championship",
            "primary_color_hex": "#20429a",
            "secondary_color_hex": "#ac944a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/18/image",
            "tier": 2,
            "most_titles": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-04",
            "end_date": "2024-05-26",
            "play_zone": 7
        },
        {
            "league_title": "League One",
            "slug": "league-one",
            "primary_color_hex": "#20429a",
            "secondary_color_hex": "#848888",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/24/image",
            "most_titles": 3,
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-04",
            "end_date": "2024-05-18",
            "play_zone": 7
        },
        {
            "league_title": "League Two",
            "slug": "league_two",
            "primary_color_hex": "#20429a",
            "secondary_color_hex": "#be0008",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/25/image",
            "most_titles": 2,
            "tier": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-04",
            "end_date": "2024-05-19",
            "play_zone": 7
        },
        {
            "league_title": "National League",
            "slug": "national-league",
            "primary_color_hex": "#1d1e1e",
            "secondary_color_hex": "#eb6620",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/173/image",
            "most_titles": 3,
            "tier": 5,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2024-05-05",
            "play_zone": 7
        },
        {
            "league_title": "FA Cup",
            "slug": "fa-cup",
            "primary_color_hex": "#bc1821",
            "secondary_color_hex": "#e60411",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19/image",
            "most_titles": 14,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-11-03",
            "end_date": "2024-05-25",
            "play_zone": 7
        },
        {
            "league_title": "FA Cup, Qualification",
            "slug": "fa-cup-qualification",
            "primary_color_hex": "#002b80",
            "secondary_color_hex": "#e60414",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1696/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-01",
            "end_date": "2024-01-31",
            "play_zone": 7
        },
        {
            "league_title": "EFL Cup",
            "slug": "efl-cup",
            "primary_color_hex": "#203e93",
            "secondary_color_hex": "#bc1723",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/21/image",
            "most_titles": 10,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-08",
            "end_date": "2024-02-25",
            "play_zone": 7
        },
        {
            "league_title": "Football League Trophy",
            "slug": "football-league-trophy",
            "primary_color_hex": "#0076c0",
            "secondary_color_hex": "#e60414",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/334/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-22",
            "end_date": "2023-04-07",
            "play_zone": 7
        },
        {
            "league_title": "FA Women`s Championship",
            "slug": "fa-womens-championship",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/10553/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-26",
            "end_date": "2024-04-28",
            "play_zone": 7
        },
        {
            "league_title": "Community Shield",
            "slug": "community-shield",
            "primary_color_hex": "#e4051f",
            "secondary_color_hex": "#949fa4",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/346/image",
            "most_titles": 21,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-06",
            "end_date": "2023-08-07",
            "play_zone": 7
        },
        {
            "league_title": "The FA Women`s Super League",
            "slug": "the-fa-womens-super-league",
            "primary_color_hex": "#1c0f3",
            "secondary_color_hex": "#fc4342",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1044/image",
            "most_titles": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-10-01",
            "end_date": "2024-05-18",
            "play_zone": 7
        },
        {
            "league_title": "FA Cup, Women",
            "slug": "fa-cup-women",
            "primary_color_hex": "#f41e60",
            "secondary_color_hex": "#98989a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/11666/image",
            "most_titles": 14,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-11-11",
            "end_date": "2024-05-12",
            "play_zone": 7
        },
        {
            "league_title": "FA Women`s League Cup",
            "slug": "fa-womens-league-cup",
            "secondary_color_hex": "#ffac00",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/11667/image",
            "most_titles": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-10-11",
            "end_date": "2024-05-03",
            "play_zone": 7
        },
        {
            "league_title": "National League North",
            "slug": "national-league-north",
            "primary_color_hex": "#ff730b",
            "secondary_color_hex": "#e83300",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/176/image",
            "most_titles": 0,
            "tier": 6,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2024-05-04",
            "play_zone": 24
        },
        {
            "league_title": "National League South",
            "slug": "national-league-south",
            "primary_color_hex": "#ff730b",
            "secondary_color_hex": "#e83300",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/174/image",
            "most_titles": 0,
            "tier": 6,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2024-05-04",
            "play_zone": 24
        },
        {
            "league_title": "Northern Premier League, Premier Division",
            "slug": "northern-premier-league-premier-division",
            "primary_color_hex": "#5a57a5",
            "secondary_color_hex": "#bcbdbf",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1111/image",
            "most_titles": 0,
            "tier": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-12",
            "end_date": "2024-05-06",
            "play_zone": 24
        },
        {
            "league_title": "Southern Premier League, Premier Division Central",
            "slug": "southern-premier-league-premier-division-central",
            "primary_color_hex": "#2d2b95",
            "secondary_color_hex": "#ff3637",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/11342/image",
            "most_titles": 0,
            "tier": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2024-05-06",
            "play_zone": 24
        },
        {
            "league_title": "Southern Football League, Premier Division South",
            "slug": "southern-football-league-premier-division-south",
            "primary_color_hex": "#2d2b95",
            "secondary_color_hex": "#ff3637",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/11340/image",
            "most_titles": 0,
            "tier": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2024-05-06",
            "play_zone": 24
        },
        {
            "league_title": "Isthmian League, Division One North",
            "slug": "isthmian-league-division-one-north",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19275/image",
            "tier": 9,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-05-31",
            "play_zone": 24
        },
        {
            "league_title": "Isthmian League, Division One South Central",
            "slug": "isthmian-league-division-one-south-central",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/17242/image",
            "tier": 8,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-12",
            "end_date": "2024-04-27",
            "play_zone": 24
        },
        {
            "league_title": "Isthmian Football League, Premier Division",
            "slug": "isthmian-football-league-premier-division",
            "primary_color_hex": "#fdef4b",
            "secondary_color_hex": "#7fc249",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1131/image",
            "tier": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-12",
            "end_date": "2024-05-06",
            "play_zone": 24
        },
        {
            "league_title": "Isthmian League, South West Divison",
            "slug": "isthmian-league-south-west-division",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19126/image",
            "tier": 8,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-07-29",
            "end_date": "2024-05-11",
            "play_zone": 24
        },
        {
            "league_title": "Isthmian Football League, North Division",
            "slug": "isthmian-football-league-north-division",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/17142/image",
            "tier": 8,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-14",
            "end_date": "2024-04-23",
            "play_zone": 24
        },
        {
            "league_title": "Northern Premier League Division One East",
            "slug": "northern-premier-league-division-one-east",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/21485/image",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-12",
            "end_date": "2024-06-30",
            "play_zone": 24
        },
        {
            "league_title": "Velocity Wessex League Premier Division",
            "slug": "velocity-wessex-league-premier-division",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/21955/image",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-26",
            "end_date": "2024-06-30",
            "play_zone": 24
        },
        {
            "league_title": "Cherry Red Records Combined Counties - Premier Division South",
            "slug": "cherry-red-records-combined-counties-premier-division-south",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-09",
            "end_date": "2023-04-27",
            "play_zone": 24
        },
        {
            "league_title": "FA Trophy",
            "slug": "fa-trophy",
            "primary_color_hex": "#575556",
            "secondary_color_hex": "#de1412",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/628/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-10-27",
            "end_date": "2024-05-12",
            "play_zone": 24
        },
        {
            "league_title": "FA Trophy, Qualification",
            "slug": "fa-trophy-qualification",
            "primary_color_hex": "#575556",
            "secondary_color_hex": "#de1412",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1991/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-23",
            "end_date": "2023-10-08",
            "play_zone": 24
        },
        {
            "league_title": "Velocity Trophy",
            "slug": "velocity-trophy",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-05",
            "end_date": "2024-04-05",
            "play_zone": 24
        },
        {
            "league_title": "Premier League 2, Division 1",
            "slug": "premier-league-2-division-1",
            "primary_color_hex": "#3c1c5a",
            "secondary_color_hex": "#67c079",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1129/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-05-31",
            "play_zone": 24
        },
        {
            "league_title": "Premier League 2, Division 2",
            "slug": "premier-league-2-division-2",
            "primary_color_hex": "#3c1c5a",
            "secondary_color_hex": "#67c079",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19070/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2024-05-31",
            "play_zone": 24
        },
        {
            "league_title": "Professional Development League",
            "slug": "professional-development-league",
            "primary_color_hex": "#3c1c5a",
            "secondary_color_hex": "#f80158",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/13946/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-12",
            "end_date": "2023-05-30",
            "play_zone": 24
        },
        {
            "league_title": "Premier League Cup",
            "slug": "premier-league-cup",
            "primary_color_hex": "#351761",
            "secondary_color_hex": "#bb59d9",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1592/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-18",
            "end_date": "2024-05-31",
            "play_zone": 24
        },
        {
            "league_title": "The Conquest Cup",
            "slug": "the-conquest-cup",
            "primary_color_hex": "#788AC5",
            "secondary_color_hex": "#6A6FB5",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/20438/image",
            "most_titles": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-06-03",
            "end_date": "2023-06-04",
            "play_zone": 24,
        },
        {
            "league_title": "Content Creators Cup",
            "slug": "content-creators-cup",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/20343/image",
            "most_titles": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "play_zone": 24
        },
        {
            "league_title": "Social Series Cup",
            "slug": "social-series-cup",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/20349/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-05-06",
            "end_date": "2023-05-07",
            "play_zone": 24
        },
        {
            "league_title": "Eastern Counties League Premier Division",
            "slug": "eastern-counties-league-premier-division",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/22205/image",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-05",
            "end_date": "2024-06-30",
            "play_zone": 24
        },
        {
            "league_title": "Southern Combination League Premier Division",
            "slug": "southern-combination-league-premier-division",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-29",
            "end_date": "2024-04-20",
            "play_zone": 24
        },
        {
            "league_title": "Girabola",
            "slug": "girabola",
            "primary_color_hex": "#cc0000",
            "secondary_color_hex": "#b09648",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2308/image",
            "most_titles": 17,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-10-28",
            "end_date": "2023-06-31",
            "play_zone": 25
        },
        {
            "league_title": "Primera Divisió",
            "slug": "primera-divisio",
            "primary_color_hex": "#1B47A3",
            "secondary_color_hex": "#FC9E17",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/742/image",
            "tier": 1,
            "most_titles": 13,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-16",
            "end_date": "2024-05-31",
            "play_zone": 26
        },
        {
            "league_title": "Segona Divisió",
            "slug": "segona-divisio",
            "primary_color_hex": "#0054a9",
            "secondary_color_hex": "#df0309",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/743/image",
            "most_titles": 1,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-23",
            "end_date": "2024-05-19",
            "play_zone": 26
        },
        {
            "league_title": "Copa Constitució",
            "slug": "copa-constitucio",
            "primary_color_hex": "#0054a9",
            "secondary_color_hex": "#df0309",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/881/image",
            "most_titles": 9,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-01-14",
            "end_date": "2024-06-26",
            "play_zone": 26
        },
        {
            "league_title": "Super Cup",
            "slug": "super-cup",
            "primary_color_hex": "#0054a9",
            "secondary_color_hex": "#df0309",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/16589/image",
            "most_titles": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-27",
            "end_date": "2023-09-28",
            "play_zone": 26
        },
        {
            "league_title": "ABFA Premier League",
            "slug": "abfa-premier-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19790/image",
            "tier": 1,
            "most_titles": 13,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-11-25",
            "end_date": "2024-03-24",
            "play_zone": 27
        },
        {
            "league_title": "Liga Profesional de Fútbol",
            "slug": "liga-profesional-de-futbol",
            "primary_color_hex": "#0cbad8",
            "secondary_color_hex": "#daa813",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/155/image",
            "most_titles": 38,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-05-04",
            "end_date": "2024-12-16",
            "play_zone": 28
        },
        {
            "league_title": "Copa de la Liga Profesional",
            "slug": "copa-de-la-liga-profesional",
            "primary_color_hex": "#0cbad8",
            "secondary_color_hex": "#daa813",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/13475/image",
            "most_titles": 2,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-01-25",
            "end_date": "2024-12-18",
            "play_zone": 28
        },
        {
            "league_title": "Copa Argentina",
            "slug": "copa-argentina",
            "primary_color_hex": "#187ec0",
            "secondary_color_hex": "#44a4d8",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1024/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-01-25",
            "end_date": "2024-12-31",
            "play_zone": 28
        },
        {
            "league_title": "Primera Nacional",
            "slug": "primera-nacional",
            "primary_color_hex": "#145286",
            "secondary_color_hex": "#27A4DE",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/703/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-02-02",
            "end_date": "2024-12-07",
            "play_zone": 28
        },
        {
            "league_title": "Primera B",
            "slug": "primera-b",
            "primary_color_hex": "#0098da",
            "secondary_color_hex": "#B19355",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1347/image",
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-02-02",
            "end_date": "2024-12-16",
            "play_zone": 28
        },
        {
            "league_title": "Primera C Metropolitana",
            "slug": "primera-c-metropolitana",
            "primary_color_hex": "#1fdbff",
            "secondary_color_hex": "#B19355",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/11386/image",
            "most_titles": 7,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-02-02",
            "end_date": "2024-12-16",
            "play_zone": 28
        },
        {
            "league_title": "Primera D Metropolitana",
            "slug": "primera-d-metropolitana",
            "primary_color_hex": "#1edeff",
            "secondary_color_hex": "#00bedf",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14101/image",
            "tier": 5,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-05-18",
            "end_date": "2023-11-30",
            "play_zone": 28
        },
        {
            "league_title": "Torneo Federal A",
            "slug": "torneo-federal-a",
            "primary_color_hex": "#00b0d8",
            "secondary_color_hex": "#ff8c00",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14090/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-03-22",
            "end_date": "2024-12-02",
            "play_zone": 28
        },
        {
            "league_title": "Supercopa Argentina",
            "slug": "supercopa-argentina",
            "primary_color_hex": "#7c87a0",
            "secondary_color_hex": "#505969",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1618/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-13",
            "end_date": "2024-03-14",
            "play_zone": 28
        },
        {
            "league_title": "Torneos de Verano",
            "slug": "torneos-de-verano",
            "primary_color_hex": "#c00212",
            "secondary_color_hex": "#d7ad09",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1230/image",
            "most_titles": 46,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-01-11",
            "end_date": "2024-01-21",
            "play_zone": 28
        },
        {
            "league_title": "Primera Division, Women",
            "slug": "primera-division-women",
            "primary_color_hex": "#C09C5E",
            "secondary_color_hex": "#ccaa71",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/10495/image",
            "most_titles": 27,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-09",
            "end_date": "2024-12-16",
            "play_zone": 28
        },
        {
            "league_title": "Trofeo de Campeones de la Liga Profesional",
            "slug": "trofeo-de-campeones-de-la-liga-profesional",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/18436/image",
            "most_titles": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-12-22",
            "end_date": "2023-12-23",
            "play_zone": 28
        },
        {
            "league_title": "Campeonato de Reserva de Primera Division",
            "slug": "campeonato-de-reserva-de-primera-division",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/18817/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-01-26",
            "end_date": "2023-08-07",
            "play_zone": 28
        },
        {
            "league_title": "Copa de la Liga, Reserves",
            "slug": "copa-de-la-liga-reserves",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-06",
            "end_date": "2024-12-31",
            "play_zone": 28
        },
        {
            "league_title": "Copa de la Liga, Women",
            "slug": "copa-de-la-liga-women",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "most_titles": 27,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-19",
            "end_date": "2023-12-13"
        },
        {
            "league_title": "Supercopa Internacional",
            "slug": "supercopa-internacional",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19841/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-01-20",
            "end_date": "2023-01-21",
            "play_zone": 28
        },
        {
            "league_title": "Torneo Promocional Ameteur",
            "slug": "torneo-promocional-amteur",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/22012/image",
        }
    ]

    LEAGUES = [
        {
            "league_title": "UEFA Champions League",
            "slug": "uefa-champions-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/7/image",
            "primary_color_hex": "#062b5c",
            "secondary_color_hex": "#086aab",
            "most_titles": 14,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-06-27",
            "end_date": "2024-06-01",
            "play_zone": 1
        },
        {
            "league_title": "UEFA Europa League",
            "slug": "uefa-europa-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/679/image",
            "primary_color_hex": "",
            "secondary_color_hex": "#f37d25",
            "most_titles": 7,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-08",
            "end_date": "2024-05-22",
            "play_zone": 1
        },
        {
            "league_title": "Premier League",
            "slug": "premier-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/17/image",
            "primary_color_hex": "#3c1c5a",
            "secondary_color_hex": "#f80158",
            "most_titles": 20,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": True,
            "has_playoff_series": False,
            "tier": 1,
            "start_date": "2023-08-11",
            "end_date": "2024-05-19",
            "play_zone": 7
        },
        {
            "league_title": "European Championship",
            "slug": "european-championship",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1/image",
            "primary_color_hex": "#293cdb",
            "secondary_color_hex": "#00ba5d",
            "most_titles": 3,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-06-14",
            "end_date": "2024-07-14",
            "play_zone": 1
        },
        {
            "league_title": "Copa América",
            "slug": "copa-america",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/133/image",
            "primary_color_hex": "#0A2357",
            "secondary_color_hex": "#F70F17",
            "most_titles": 15,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disable_home_away_standings": True,
            "start_date": "2024-06-20",
            "end_date": "2024-07-14",
            "play_zone": 4,
        },
        {
            "league_title": "LaLiga",
            "slug": "laliga",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/8/image",
            "primary_color_hex": "#2f4a89",
            "secondary_color_hex": "#f4a32e",
            "most_titles": 35,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-05-26",
            "play_zone": 8
        },
        {
            "league_title": "Bundesliga",
            "slug": "bundesliga",
            "primary_color_hex": "#e2080e",
            "secondary_color_hex": "#8e090",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/35/image",
            "most_titles": 32,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-18",
            "end_date": "2024-05-28",
            "play_zone": 9
        },
        {
            "league_title": "Serie A",
            "slug": "seria-a",
            "primary_color_hex": "#09519e",
            "secondary_color_hex": "#008fd7",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/23/image",
            "most_titles": 36,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-08-19",
            "end_date": "2024-06-02",
            "play_zone": 10
        },
        {
            "league_title": "Ligue 1",
            "slug": "ligue-1",
            "primary_color_hex": "#091c3e",
            "secondary_color_hex": "#a9c011",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/34/image",
            "most_titles": 11,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-06-03",
            "play_zone": 11
        },
        {
            "league_title": "Eredivisie",
            "slug": "eredivisie",
            "primary_color_hex": "#292766",
            "secondary_color_hex": "#7c79c3",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/37/image",
            "most_titles": 36,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-06-02",
            "play_zone": 12
        },
        {
            "league_title": "Brasileirão Serie A",
            "slug": "brasileirao-serie-a",
            "primary_color_hex": "#C7FF00",
            "secondary_color_hex": "#969696",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/325/image",
            "most_titles": 12,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-04-13",
            "end_date": "2024-12-09",
            "play_zone": 13
        },
        {
            "league_title": "CONMEBOL Libertadores",
            "slug": "conmebol-libertadores",
            "primary_color_hex": "#57321",
            "secondary_color_hex": "#dfaf49",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/384/image",
            "most_titles": 7,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-02-06",
            "end_date": "2024-12-01",
            "play_zone": 4
        },
        {
            "league_title": "CAF Champions League",
            "slug": "caf-champions_league",
            "primary_color_hex": "#ebbf03",
            "secondary_color_hex": "#3a292a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1054/image",
            "most_titles": 11,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-18",
            "end_date": "2024-05-26",
            "play_zone": 3
        },
        {
            "league_title": "Premier League",
            "slug": "premier-league",
            "primary_color_hex": "#15047",
            "secondary_color_hex": "#da1a32",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/218/image",
            "most_titles": 16,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-28",
            "end_date": "2024-06-03",
            "play_zone": 14
        },
        {
            "league_title": "World Championship",
            "slug": "world-championship",
            "primary_color_hex": "#d20a11",
            "secondary_color_hex": "#e8bb57",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/16/image",
            "most_titles": 5,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disable_home_away_standings": True,
            "start_date": "2022-11-20",
            "end_date": "2022-12-18",
            "play_zone": 15
        }
    ]

    RATINGS = [
        {
            "rating_logo": "https://www.sofascore.com/static/images/flags/fifa-big.png",
            "rating_title": "FIFA Рейтинг"
        },
        {
            "rating_logo": "https://www.sofascore.com/static/images/flags/uefa-big.png",
            "rating_title": "UEFA Рейтинг"
        }
    ]

