from dataclasses import dataclass
import datetime


@dataclass
class DataStorage:
    PLAY_ZONES = [
        {
            "id": 1,
            "play_zone_title": "Європа",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/europe.png"
        },
        {
            "id": 2,
            "play_zone_title": "Азія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/asia.png"
        },
        {
            "id": 3,
            "play_zone_title": "Африка",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/africa.png"
        },
        {
            "id": 4,
            "play_zone_title": "Південна Америка",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/south-america.png",
        },
        {
            "id": 5,
            "play_zone_title": "Північна & Центральна Америка",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/north-and-central-america.png"
        },
        {
            "id": 6,
            "play_zone_title": "Океанія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/oceania.png"
        },
        {
            "id": 7,
            "play_zone_title": "Англія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/en.png"
        },
        {
            "id": 8,
            "play_zone_title": "Іспанія",
            "play_zone_area_image": 'https://www.sofascore.com/static/images/flags/es.png'
        },
        {
            "id": 9,
            "play_zone_title": "Німеччина",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/de.png"
        },
        {
            "id": 10,
            "play_zone_title": "Італія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/it.png"
        },
        {
            "id": 11,
            "play_zone_title": "Франція",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/fr.png"
        },
        {
            "id": 12,
            "play_zone_title": "Нідерланди",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/nl.png"
        },
        {
            "id": 13,
            "play_zone_title": "Бразилія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/br.png"
        },
        {
            "id": 14,
            "play_zone_title": "Україна",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/ua.png"
        },
        {
            "id": 15,
            "play_zone_title": "Історія чемпіонату світу",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/international.png"
        },
        {
            "id": 16,
            "play_zone_title": "Австралія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/au.png"
        },
        {
            "id": 17,
            "play_zone_title": "Австрія",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/at.png"
        },
        {
            "id": 18,
            "play_zone_title": "Австрія Любительська",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/at.png"
        },
        {
            "id": 19,
            "play_zone_title": "Азербайджан",
            "play_zone_area_image": "https://www.sofascore.com/static/images/flags/az.png"
        }
    ]

    ALL_LEAGUES = [
        {
            "league_title": "A-League Men",
            "slug": "a-league-men",
            "primary_color_hex": "#fe5001",
            "secondary_color_hex": "#8e0a06",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/136/image",
            "most_titles": 5,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-10-26",
            "end_date": "2024-05-31",
            "play_zone": 16
        },
        {
            "league_title": "A-League Women",
            "slug": "a-league-women",
            "primary_color_hex": "#a21c13",
            "secondary_color_hex": "#e44134",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/136/image",
            "most_titles": 4,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-10-13",
            "end_date": "2024-05-04",
            "play_zone": 16
        },
        {
            "league_title": "Australia Cup",
            "slug": "australia-cup",
            "primary_color_hex": "#16263c",
            "secondary_color_hex": "#6895cf",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1786/image",
            "most_titles": 3,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-17",
            "end_date": "2023-10-09",
            "play_zone": 16
        },
        {
            "league_title": "National Premier League Finals",
            "slug": "national-premier-league-finals",
            "primary_color_hex": "#0c2340",
            "secondary_color_hex": "#0086e1",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1510/image",
            "most_titles": 0,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-21",
            "end_date": "2023-10-07",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Capital Football",
            "slug": "npm-capital-football",
            "primary_color_hex": "#1483be",
            "secondary_color_hex": "#189ce6",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1260/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-04-05",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, New South Wales",
            "slug": "npm-new-south-wales",
            "primary_color_hex": "#5ab6e6",
            "secondary_color_hex": "#1b4880",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1274/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-16",
            "end_date": "2024-09-08",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Northern New South Wales",
            "slug": "npl-northern-new-south-wales",
            "primary_color_hex": "#b5151b",
            "secondary_color_hex": "ed1c24",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1638/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-11",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Queensland",
            "slug": "npl-queensland",
            "primary_color_hex": "#53081e",
            "secondary_color_hex": "#ba1b53",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1268/image",
            "most_titles": 3,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-06",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Queensland, Women",
            "slug": "npl-queensland-women",
            "primary_color_hex": "#53081e",
            "secondary_color_hex": "#ba1b53",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/10476/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-09",
            "end_date": "2024-09-06",
            "play_zone": 16
        },
        {
            "league_title": "NPL, South Australia",
            "slug": "npl-south-australia",
            "primary_color_hex": "#004f8b",
            "secondary_color_hex": "#c31c34",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1258/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, South Australia, Women",
            "slug": "npl-south-australia-women",
            "primary_color_hex": "#004f8b",
            "secondary_color_hex": "#c31c34",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14723/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-15",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Tasmania",
            "slug": "npl-tasmania",
            "primary_color_hex": "#009f46",
            "secondary_color_hex": "#005c2f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1626/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-15",
            "end_date": "2024-10-30",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Victoria",
            "slug": "npl-victoria",
            "primary_color_hex": "#005e9c",
            "secondary_color_hex": "#004673",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1275/image",
            "most_titles": 4,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-08",
            "end_date": "2024-09-08",
            "play_zone": 16
        },
        {
            "league_title": "NPL, Western Australia",
            "slug": "npl-western-australia",
            "primary_color_hex": "#ffb20e",
            "secondary_color_hex": "#694c06",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1270/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-16",
            "end_date": "2024-09-30",
            "play_zone": 16
        },
        {
            "league_title": "Brisbane Premier League",
            "slug": "brisbane-premier-league",
            "primary_color_hex": "#979691",
            "secondary_color_hex": "#4388cd",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1248/image",
            "most_tiles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-03-05",
            "end_date": "2024-10-17",
            "play_zone": 16
        },
        {
            "league_title": "Brisbane Premier League, Women",
            "slug": "brisbane-premier-league-women",
            "primary_color_hex": "#0fbaf2",
            "secondary_color_hex": "#0ea3d3",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14722/image",
            "most_titles": 0,
            "tier": 2,
            "start_date": "2024-05-12",
            "end_date": "2024-10-17",
            "play_zone": 16
        },
        {
            "league_title": "A-League Youth",
            "slug": "a-league-youth",
            "primary_color_hex": "#b71100",
            "secondary_color_hex": "#ff4000",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14404/image",
            "most_titles": 0,
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-11-16",
            "end_date": "2024-02-20",
            "play_zone": 16
        },
        {
            "league_title": "Queensland Premier League 1",
            "slug": "queensland-premier-league-1",
            "icon": "https://www.sofascore.com/static/images/placeholders/tournament.svg",
            "most_titles": 0,
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-02-23",
            "end_date": "2024-09-07",
            "play_zone": 16
        },
        {
            "league_title": "Bundesliga",
            "slug": "bundesliga",
            "primary_color_hex": "#b80a0c",
            "secondary_color_hex": "#eb544a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/45/image",
            "most_titles": 32,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-28",
            "end_date": "2024-06-02",
            "play_zone": 17
        },
        {
            "league_title": "ÖFB Cup",
            "slug": "ofb-cup",
            "primary_color_hex": "#dc2e25",
            "secondary_color_hex": "#0065b1",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/445/image",
            "most_titles": 27,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-20",
            "end_date": "2024-05-01",
            "play_zone": 17
        },
        {
            "league_title": "2. Liga",
            "slug": "2-liga",
            "primary_color_hex": "#ea1013",
            "secondary_color_hex": "#b5b5b5",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/135/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-28",
            "end_date": "2024-05-26",
            "play_zone": 17,
        },
        {
            "league_title": "Frauen Bundesliga",
            "primary_color_hex": "#cc0033",
            "secondary_color_hex": "#ad536a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/9415/image",
            "most_titles": 0,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-25",
            "end_date": "2024-06-02",
            "play_zone": 17
        },
        {
            "league_title": "Regionalliga Ost",
            "slug": "regionalliga-ost",
            "primary_color_hex": "#970800",
            "secondary_color_hex": "#8d8d8d",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/166/image",
            "most_titles": 0,
            "tier": 3,
            "start_date": "2023-08-28",
            "end_date": "2024-06-02",
            "play_zone": 18
        },
        {
            "league_title": "Regionalliga Mitte",
            "slug": "regionalliga-mitte",
            "primary_color_hex": "#037a3c",
            "secondary_color_hex": "#909090",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/168/image",
            "most_titles": 0,
            "tier": 3,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-28",
            "end_date": "2024-06-09",
            "play_zone": 18
        },
        {
            "league_title": "Regionalliga West",
            "slug": "regionalliga-west",
            "primary_color_hex": "#006699",
            "secondary_color_hex": "#81c9f1",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/167/image",
            "most_titles": 0,
            "tier": 3,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-28",
            "end_date": "2024-06-09",
            "play_zone": 18
        },
        {
            "league_title": "Misli Premier League",
            "slug": "misli-premier-league",
            "primary_color_hex": "#3449b2",
            "secondary_color_hex": "#1b157f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/709/image",
            "most_titles": 10,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-04",
            "end_date": "2024-05-31",
            "play_zone": 19
        },
        {
            "league_title": "Birinci Liqa",
            "slug": "birinci-liqa",
            "primary_color_hex": "#fde900",
            "secondary_color_hex": "#01923e",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/736/image",
            "most_titles": 0,
            "tier": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-13",
            "end_date": "2024-05-31",
            "play_zone": 19
        },
        {
            "league_title": "Ikinci Liqa",
            "slug": "ikinci-liqa",
            "logo": "https://api.sofascore.app/api/v1/unique-tournament/21050/image",
            "most_titles": 0,
            "tier": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-01",
            "end_date": "2024-06-01",
            "play_zone": 19
        },
        {
            "league_title": "Azerbaijan Cup",
            "slug": "azerbaijan-cup",
            "primary_color_hex": "#a2a5ca",
            "secondary_color_hex": "#6f95b7",
            "logo": "https://api.sofascore.app/api/v1/unique-tournament/740/image",
            "most_titles": 7,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": False,
            "start_date": "2023-11-18",
            "end_date": "2024-06-02",
            "play_zone": 19
        },
        {
            "league_title": "AFC Champions League",
            "slug": "afc-champions-league",
            "primary_color_hex": "#0050d4",
            "secondary_color_hex": "#fe9700",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/463/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-15",
            "end_date": "2024-05-25",
            "play_zone": 2
        },
        {
            "league_title": "AFC Cup",
            "slug": "afc-cup",
            "primary_color_hex": "#033aa7",
            "secondary_color_hex": "#d10007",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/668/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-08",
            "end_date": "2024-05-05",
            "play_zone": 2
        },
        {
            "league_title": "World Championship Qual.AFC",
            "slug": "world-championship-qual-afc",
            "primary_color_hex": "#9a1133",
            "secondary_color_hex": "#c11541",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/308/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-10-12",
            "end_date": "2025-11-25",
            "play_zone": 2
        },
        {
            "league_title": "AFC Asian Cup",
            "slug": "afc-asian-cup",
            "primary_color_hex": "#FCBD00",
            "secondary_color_hex": "#FC1302",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/246/image",
            "most_titles": 4,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2024-01-12",
            "end_date": "2024-02-10",
            "play_zone": 2
        },
        {
            "league_title": "AFC Asian Cup Qual.",
            "slug": "afc-asian-cup-qual",
            "primary_color_hex": "#ff2816",
            "secondary_color_hex": "#bfbfbf",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/28/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2021-10-07",
            "end_date": "2022-06-14",
            "play_zone": 2
        },
        {
            "league_title": "AFC Asian Cup, Women",
            "slug": "afc-asian-cup-women",
            "primary_color_hex": "#f3a953",
            "secondary_color_hex": "#19bc55",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1692/image",
            "most_titles": 10,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-01-20",
            "end_date": "2023-02-06",
            "play_zone": 2
        },
        {
            "league_title": "AFF Mitsubishi Electric Cup",
            "slug": "aff-mitsubishi-electric-cup",
            "primary_color_hex": "#005da3",
            "secondary_color_hex": "#e31079",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/602/image",
            "most_titles": 6,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2022-12-20",
            "end_date": "2023-01-16",
            "play_zone": 2
        },
        {
            "league_title": "Asian Games",
            "slug": "asian-games",
            "primary_color_hex": "#0c3ad2",
            "secondary_color_hex": "#ad28b5",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1862/image",
            "most_titles": 6,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2023-09-19",
            "end_date": "2023-10-07",
            "play_zone": 2
        },
        {
            "league_title": "AFC Olympic Qualification, Women",
            "slug": "afc-olympic-qualification-women",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/3082/image",
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-10-26",
            "end_date": "2024-02-28",
            "play_zone": 2
        },
        {
            "league_title": "Asian Games, Women",
            "slug": "asian-games-women",
            "primary_color_hex": "#da0e7d",
            "secondary_color_hex": "#b225b7",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/11330/image",
            "most_titles": 3,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-09-21",
            "end_date": "2023-10-06",
            "play_zone": 2
        },
        {
            "league_title": "East Asian Championship",
            "slug": "east-asian-championship",
            "primary_color_hex": "#1e4559",
            "secondary_color_hex": "#7bacc4",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/392/image",
            "most_titles": 5,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2022-07-19",
            "end_date": "2022-07-28",
            "play_zone": 2
        },
        {
            "league_title": "East Asian Championship, Women",
            "slug": "east-asian-championship-women",
            "primary_color_hex": "#1e4559",
            "secondary_color_hex": "#7bacc4",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/404/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2022-07-19",
            "end_date": "2022-07-26",
            "play_zone": 2
        },
        {
            "league_title": "Gulf Cup",
            "slug": "gulf-cup",
            "primary_color_hex": "#632c31",
            "secondary_color_hex": "#c5566f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/622/image",
            "most_titles": 10,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2023-01-06",
            "end_date": "2023-01-19",
            "play_zone": 2
        },
        {
            "league_title": "King`s Cup",
            "slug": "kings-cup",
            "primary_color_hex": "#01023b",
            "secondary_color_hex": "#e8124a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/10416/image",
            "most_titles": 15,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-09-07",
            "end_date": "2023-09-10",
            "play_zone": 2
        },
        {
            "league_title": "SAFF Championship",
            "slug": "saff-championship",
            "primary_color_hex": "#8779b4",
            "secondary_color_hex": "#f27501",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2354/image",
            "most_titles": 9,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-06-21",
            "end_date": "2023-07-04",
            "play_zone": 2
        },
        {
            "league_title": "Southeast Asian Games, Women",
            "slug": "southeast-asian-games-women",
            "primary_color_hex": "#375dab",
            "secondary_color_hex": "#f8971f",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/14527/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-05-03",
            "end_date": "2023-05-15",
            "play_zone": 2
        },
        {
            "league_title": "WAFF Championship",
            "slug": "waff-championship",
            "primary_color_hex": "#ee2128",
            "secondary_color_hex": "#128e47",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/842/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disabled_home_away_standings": True,
            "start_date": "2019-07-30",
            "end_date": "2019-08-15",
            "play_zone": 2
        },
        {
            "league_title": "U23 AFC Asian Cup",
            "slug": "u23-afc-acian-cup",
            "primary_color_hex": "#73addc",
            "secondary_color_hex": "#d46c9d",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2349/image",
            "most_titles": 2,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-04-15",
            "end_date": "2024-05-03",
            "play_zone": 2
        },
        {
            "league_title": "U23 AFC Asian Cup, Qualification",
            "slug": "u23-afc-asian-cup-qualification",
            "primary_color_hex": "#73addc",
            "secondary_color_hex": "#d46c9d",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2348/image",
            "most_titles": 0,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-09-04",
            "end_date": "2023-09-12",
            "play_zone": 2
        },
        {
            "league_title": "U23 WAFF Championship",
            "slug": "u23-waff-championship",
            "primary_color_hex": "#ff0000",
            "secondary_color_hex": "#ff6a6a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/2157/image",
            "most_titles": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-03-20",
            "end_date": "2024-03-26",
            "play_zone": 2
        },
        {
            "league_title": "U20 AFC Asian Cup",
            "slug": "u20-afc-asian-cup",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/19546/image",
            "most_titles": 12,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-03-01",
            "end_date": "2023-03-18",
            "play_zone": 2
        },
        {
            "league_title": "U17 AFC Asian Cup",
            "slug": "u17-afc-asian-cup",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/20163/image",
            "most_titles": 4,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-06-15",
            "end_date": "2023-07-02",
            "play_zone": 2
        },
        {

        }
    ]

    LEAGUES = [
        {
            "league_title": "UEFA Champions League",
            "slug": "uefa-champions-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/7/image",
            "primary_color_hex": "#062b5c",
            "secondary_color_hex": "#086aab",
            "most_titles": 14,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-06-27",
            "end_date": "2024-06-01",
            "play_zone": 1
        },
        {
            "league_title": "UEFA Europa League",
            "slug": "uefa-europa-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/679/image",
            "primary_color_hex": "",
            "secondary_color_hex": "#f37d25",
            "most_titles": 7,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-08",
            "end_date": "2024-05-22",
            "play_zone": 1
        },
        {
            "league_title": "Premier League",
            "slug": "premier-league",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/17/image",
            "primary_color_hex": "#3c1c5a",
            "secondary_color_hex": "#f80158",
            "most_titles": 20,
            "has_standings_groups": False,
            "has_rounds": False,
            "has_groups": True,
            "has_playoff_series": False,
            "tier": 1,
            "start_date": "2023-08-11",
            "end_date": "2024-05-19",
            "play_zone": 7
        },
        {
            "league_title": "European Championship",
            "slug": "european-championship",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1/image",
            "primary_color_hex": "#293cdb",
            "secondary_color_hex": "#00ba5d",
            "most_titles": 3,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-06-14",
            "end_date": "2024-07-14",
            "play_zone": 1
        },
        {
            "league_title": "Copa América",
            "slug": "copa-america",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/133/image",
            "primary_color_hex": "#0A2357",
            "secondary_color_hex": "#F70F17",
            "most_titles": 15,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disable_home_away_standings": True,
            "start_date": "2024-06-20",
            "end_date": "2024-07-14",
            "play_zone": 4,
        },
        {
            "league_title": "LaLiga",
            "slug": "laliga",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/8/image",
            "primary_color_hex": "#2f4a89",
            "secondary_color_hex": "#f4a32e",
            "most_titles": 35,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-05-26",
            "play_zone": 8
        },
        {
            "league_title": "Bundesliga",
            "slug": "bundesliga",
            "primary_color_hex": "#e2080e",
            "secondary_color_hex": "#8e090",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/35/image",
            "most_titles": 32,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-18",
            "end_date": "2024-05-28",
            "play_zone": 9
        },
        {
            "league_title": "Serie A",
            "slug": "seria-a",
            "primary_color_hex": "#09519e",
            "secondary_color_hex": "#008fd7",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/23/image",
            "most_titles": 36,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-08-19",
            "end_date": "2024-06-02",
            "play_zone": 10
        },
        {
            "league_title": "Ligue 1",
            "slug": "ligue-1",
            "primary_color_hex": "#091c3e",
            "secondary_color_hex": "#a9c011",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/34/image",
            "most_titles": 11,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-06-03",
            "play_zone": 11
        },
        {
            "league_title": "Eredivisie",
            "slug": "eredivisie",
            "primary_color_hex": "#292766",
            "secondary_color_hex": "#7c79c3",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/37/image",
            "most_titles": 36,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-08-11",
            "end_date": "2024-06-02",
            "play_zone": 12
        },
        {
            "league_title": "Brasileirão Serie A",
            "slug": "brasileirao-serie-a",
            "primary_color_hex": "#C7FF00",
            "secondary_color_hex": "#969696",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/325/image",
            "most_titles": 12,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2024-04-13",
            "end_date": "2024-12-09",
            "play_zone": 13
        },
        {
            "league_title": "CONMEBOL Libertadores",
            "slug": "conmebol-libertadores",
            "primary_color_hex": "#57321",
            "secondary_color_hex": "#dfaf49",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/384/image",
            "most_titles": 7,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2024-02-06",
            "end_date": "2024-12-01",
            "play_zone": 4
        },
        {
            "league_title": "CAF Champions League",
            "slug": "caf-champions_league",
            "primary_color_hex": "#ebbf03",
            "secondary_color_hex": "#3a292a",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/1054/image",
            "most_titles": 11,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "start_date": "2023-08-18",
            "end_date": "2024-05-26",
            "play_zone": 3
        },
        {
            "league_title": "Premier League",
            "slug": "premier-league",
            "primary_color_hex": "#15047",
            "secondary_color_hex": "#da1a32",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/218/image",
            "most_titles": 16,
            "tier": 1,
            "has_standings_groups": False,
            "has_rounds": True,
            "has_groups": False,
            "has_playoff_series": False,
            "start_date": "2023-07-28",
            "end_date": "2024-06-03",
            "play_zone": 14
        },
        {
            "league_title": "World Championship",
            "slug": "world-championship",
            "primary_color_hex": "#d20a11",
            "secondary_color_hex": "#e8bb57",
            "icon": "https://api.sofascore.app/api/v1/unique-tournament/16/image",
            "most_titles": 5,
            "tier": 1,
            "has_standings_groups": True,
            "has_rounds": True,
            "has_groups": True,
            "has_playoff_series": False,
            "has_disable_home_away_standings": True,
            "start_date": "2022-11-20",
            "end_date": "2022-12-18",
            "play_zone": 15
        }
    ]

    RATINGS = [
        {
            "rating_logo": "https://www.sofascore.com/static/images/flags/fifa-big.png",
            "rating_title": "FIFA Рейтинг"
        },
        {
            "rating_logo": "https://www.sofascore.com/static/images/flags/uefa-big.png",
            "rating_title": "UEFA Рейтинг"
        }
    ]

