# Generated by Django 4.1.13 on 2024-06-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sign_in_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
