# Generated by Django 4.1.13 on 2024-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuser_google_id_customuser_sign_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
