# Generated by Django 4.1.13 on 2024-07-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_customuser_facebook_id_alter_customuser_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
