# Generated by Django 4.1.13 on 2024-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_customuser_last_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_spam_subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
