# Generated by Django 4.1.13 on 2024-05-27 14:38

from django.db import migrations, models
import django.db.models.deletion
import soccer.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('alpha2', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PlayZones',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('play_zone_title', models.CharField(default='', max_length=50)),
                ('play_zone_area_image', models.URLField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_logo', models.URLField(default='', max_length=255)),
                ('rating_title', models.CharField(default='', max_length=100)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=155)),
                ('slug', models.SlugField(default='')),
                ('short_name', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('subscribers_count', models.PositiveIntegerField(default=0)),
                ('name_code', models.CharField(default='', max_length=3)),
                ('disabled', models.BooleanField(default=False)),
                ('national', models.BooleanField(default=False)),
                ('team_color_primary', models.CharField(default='#ffffff', max_length=7)),
                ('team_color_secondary', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('country', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.countries')),
            ],
            bases=(models.Model, soccer.mixins.SubscribersMixin),
        ),
        migrations.CreateModel(
            name='LeaguesModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('league_title', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='')),
                ('primary_color_hex', models.CharField(default='#fa5001', max_length=7)),
                ('secondary_color_hex', models.CharField(default='#8e0a06', max_length=7)),
                ('tier', models.IntegerField(default=1)),
                ('most_titles', models.IntegerField(default=1)),
                ('has_standings_groups', models.BooleanField(default=False)),
                ('has_rounds', models.BooleanField(default=False)),
                ('has_groups', models.BooleanField(default=False)),
                ('has_playoff_series', models.BooleanField(default=False)),
                ('has_disable_home_away_standings', models.BooleanField(default=False)),
                ('subscribers_count', models.PositiveIntegerField(default=0)),
                ('title_holder_titles', models.PositiveIntegerField(default=0)),
                ('icon', models.URLField(default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lower_divisions', models.ManyToManyField(blank=True, related_name='lower_leagues', to='soccer.leaguesmodels')),
                ('most_titles_teams', models.ManyToManyField(blank=True, related_name='most_titles_team', to='soccer.teams')),
                ('play_zone', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.playzones')),
                ('similar_divisions', models.ManyToManyField(blank=True, related_name='similar_league', to='soccer.leaguesmodels')),
                ('title_holder', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='title_holder_team', to='soccer.teams')),
                ('upper_divisions', models.ManyToManyField(blank=True, related_name='upper_leagues', to='soccer.leaguesmodels')),
            ],
            bases=(models.Model, soccer.mixins.SubscribersMixin),
        ),
    ]
