# Generated by Django 5.0.5 on 2024-05-15 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayZones',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('play_zone_title', models.CharField(default='', max_length=50)),
                ('play_zone_area_image', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesModels',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bc17c767-3987-4359-9caf-eb08092eda31'), editable=False, primary_key=True, serialize=False)),
                ('league_title', models.CharField(default='', max_length=200)),
                ('icon', models.URLField(max_length=255)),
                ('start_date', models.DateField(default='')),
                ('end_date', models.DateField(default='')),
                ('league_description', models.TextField(default='')),
                ('league_format', models.TextField(default='')),
                ('commands_stadiums', models.TextField(default='')),
                ('tv_partners', models.TextField(default='')),
                ('best_scorers', models.TextField(default='')),
                ('most_titles', models.TextField(default='')),
                ('current_winner', models.TextField(default='')),
                ('league_rang', models.TextField(default='')),
                ('average_goals', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lower_league_id', models.CharField(default='')),
                ('similar_league_id', models.CharField(default='')),
                ('command_count', models.IntegerField()),
                ('play_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.playzones')),
            ],
        ),
    ]
