# Generated by Django 5.0.5 on 2024-05-16 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesmodels',
            name='average_goals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='leaguesmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99020357-e3ef-48a7-9fc7-cfc4bd2e9d75'), editable=False, primary_key=True, serialize=False),
        ),
    ]
