# Generated by Django 4.1.13 on 2024-05-17 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='has_disable_home_away_standings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='has_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='has_playoff_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='has_rounds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='has_standings_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='icon',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='league_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='most_titles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='play_zone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.playzones'),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='primary_color_hex',
            field=models.CharField(default='#fa5001', max_length=7),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='secondary_color_hex',
            field=models.CharField(default='#8e0a06', max_length=7),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguesmodels',
            name='tier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playzones',
            name='play_zone_area_image',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='playzones',
            name='play_zone_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_logo',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaguesmodels',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playzones',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
