# Generated by Django 4.1.13 on 2024-05-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesmodels',
            name='title_holder',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_holder_team', to='soccer.teams'),
        ),
    ]
