# Generated by Django 5.0.5 on 2024-05-16 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_alter_leaguesmodels_average_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesmodels',
            name='average_goals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='leaguesmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa241914-fb8b-4c2e-998a-a2d2cd6cc2ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
