# Generated by Django 4.1.13 on 2024-06-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_alter_leaguesmodels_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playzones',
            name='play_zone_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
