# Generated by Django 4.1.13 on 2024-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_alter_leaguesmodels_title_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesmodels',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguesmodels',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
