# Generated by Django 4.1.13 on 2024-05-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_alter_leaguesmodels_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['name']},
        ),
    ]
