# Generated by Django 5.0.5 on 2024-05-16 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_alter_leaguesmodels_average_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesmodels',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
