# Generated by Django 5.0.5 on 2024-05-16 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_alter_leaguesmodels_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_logo', models.URLField(default='', max_length=255)),
                ('rating_title', models.CharField(default='', max_length=100)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
