# Generated by Django 4.1.13 on 2024-06-04 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_alter_countries_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.countries')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='foundation_timestamp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('capacity', models.IntegerField(blank=True, default=0)),
                ('city', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=200)),
                ('short_name', models.CharField(blank=True, default='', max_length=140)),
                ('country', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.countries')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='city',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.cities'),
        ),
        migrations.AddField(
            model_name='teams',
            name='manager',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.managers'),
        ),
        migrations.AddField(
            model_name='teams',
            name='stadium',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='soccer.stadiums'),
        ),
    ]
