# Generated by Django 4.1.13 on 2024-06-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0005_cities_teams_foundation_timestamp_stadiums_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadiums',
            name='city',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
