# Generated by Django 4.1.13 on 2024-06-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0006_alter_stadiums_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadiums',
            name='city',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
